var namespaceBASCloud =
[
    [ "APIContext", "classBASCloud_1_1APIContext.html", "classBASCloud_1_1APIContext" ],
    [ "BadRequest", "classBASCloud_1_1BadRequest.html", "classBASCloud_1_1BadRequest" ],
    [ "ConflictRequest", "classBASCloud_1_1ConflictRequest.html", "classBASCloud_1_1ConflictRequest" ],
    [ "ConnectionError", "classBASCloud_1_1ConnectionError.html", "classBASCloud_1_1ConnectionError" ],
    [ "Connector", "classBASCloud_1_1Connector.html", "classBASCloud_1_1Connector" ],
    [ "Device", "classBASCloud_1_1Device.html", "classBASCloud_1_1Device" ],
    [ "Entity", "classBASCloud_1_1Entity.html", "classBASCloud_1_1Entity" ],
    [ "EntityContext", "classBASCloud_1_1EntityContext.html", "classBASCloud_1_1EntityContext" ],
    [ "EntityDateMixin", "classBASCloud_1_1EntityDateMixin.html", "classBASCloud_1_1EntityDateMixin" ],
    [ "EntityTenantMixin", "classBASCloud_1_1EntityTenantMixin.html", "classBASCloud_1_1EntityTenantMixin" ],
    [ "InvalidResponse", "classBASCloud_1_1InvalidResponse.html", "classBASCloud_1_1InvalidResponse" ],
    [ "NotFoundRequest", "classBASCloud_1_1NotFoundRequest.html", "classBASCloud_1_1NotFoundRequest" ],
    [ "PagingOption", "classBASCloud_1_1PagingOption.html", "classBASCloud_1_1PagingOption" ],
    [ "PagingResult", "namespaceBASCloud.html#structBASCloud_1_1PagingResult", "namespaceBASCloud_structBASCloud_1_1PagingResult_dup" ],
    [ "Property", "classBASCloud_1_1Property.html", "classBASCloud_1_1Property" ],
    [ "Reading", "classBASCloud_1_1Reading.html", "classBASCloud_1_1Reading" ],
    [ "ServerError", "classBASCloud_1_1ServerError.html", "classBASCloud_1_1ServerError" ],
    [ "SetPoint", "classBASCloud_1_1SetPoint.html", "classBASCloud_1_1SetPoint" ],
    [ "Tenant", "classBASCloud_1_1Tenant.html", "classBASCloud_1_1Tenant" ],
    [ "UnauthorizedRequest", "classBASCloud_1_1UnauthorizedRequest.html", "classBASCloud_1_1UnauthorizedRequest" ],
    [ "User", "classBASCloud_1_1User.html", "classBASCloud_1_1User" ],
    [ "Util", "classBASCloud_1_1Util.html", null ]
];