# GLOBAL TEST VARIABLES

BASCLOUD_TEST_URL=""
BASCLOUD_TEST_EMAIL=""
BASCLOUD_TEST_ADMIN_EMAIL=""
BASCLOUD_TEST_PASS=""

BASCLOUD_TEST_USER_UUID=""
BASCLOUD_TEST_TENANT_UUID=""
BASCLOUD_TEST_PROPERTY_UUID=""
BASCLOUD_TEST_READING_UUID=""
BASCLOUD_TEST_DEVICE_UUID=""
BASCLOUD_TEST_CONNECTOR_UUID=""
BASCLOUD_TEST_STEPOINT_UUID=""

BASCLOUD_TEST_USER2_UUID=""
BASCLOUD_TEST_USER3_UUID=""

# GLOBAL TEST VARIABLES
